
(function(){
'use strict';
function q(id){return document.getElementById(id)}
function dbSave(){try{localStorage.setItem(DBKEY,JSON.stringify(db))}catch(e){console.warn(e)}}
function subjList(){try{return typeof subjects==='function'?subjects(db):[]}catch(e){return [...new Set([...(db?.customSubjects||[]),...(db?.plans||[]).map(x=>x.subject),...(db?.sessions||[]).map(x=>x.subject)].filter(Boolean))]}}
function minsForSubject(s){return (db.sessions||[]).filter(x=>x.subject===s).reduce((a,x)=>a+(Number(x.min||x.minutes)||0),0)}
function testsForSubject(s){return (db.testTasks||[]).filter(x=>x.subject===s).reduce((a,x)=>a+(Number(x.actualCount||x.count||x.tests)||0),0)+(db.sessions||[]).filter(x=>x.subject===s).reduce((a,x)=>a+(Number(x.tests)||0),0)}
function plansForSubject(s){return (db.plans||[]).filter(x=>x.subject===s).length}
function doneForSubject(s){return (db.plans||[]).filter(x=>x.subject===s&&x.done).length}
function ensureV202Data(){
 if(!db)return; db.settings=db.settings||{}; db.settings.v202Goals=db.settings.v202Goals||{dailyStudy:db.settings.goal||120,dailyTests:20,weeklyStudy:getActiveWeeklyStudyGoal?getActiveWeeklyStudyGoal():null,weeklyTests:getActiveWeeklyTestGoal?getActiveWeeklyTestGoal():null,streak:7}; db.subjectNotesPro=db.subjectNotesPro||{}; db.v202PinnedAchievements=Array.isArray(db.v202PinnedAchievements)?db.v202PinnedAchievements:[];
}
function saveGoals(){
 const g=db.settings.v202Goals||{}; ['dailyStudy','dailyTests','weeklyStudy','weeklyTests','streak'].forEach(k=>{const e=q('v202_'+k);if(e&&e.value!=='')g[k]=Math.max(1,Number(e.value)||1)}); db.settings.v202Goals=g;
 if(q('weeklyStudyGoalInput')&&g.weeklyStudy)q('weeklyStudyGoalInput').value=g.weeklyStudy;
 if(q('weeklyTestGoalInput')&&g.weeklyTests)q('weeklyTestGoalInput').value=g.weeklyTests;
 db.settings.goal=g.dailyStudy||db.settings.goal||120; dbSave(); renderGoals(); if(typeof render==='function')render();
}
function goalMetrics(){
 const now=new Date(); const today=typeof isoLocal==='function'?isoLocal(now):now.toISOString().slice(0,10); const m=(db.sessions||[]).filter(x=>x.date===today).reduce((a,x)=>a+(Number(x.min||x.minutes)||0),0); const tests=(db.testTasks||[]).filter(x=>x.date===today&&x.done).reduce((a,x)=>a+(Number(x.actualCount||x.count||x.tests)||0),0)+(db.sessions||[]).filter(x=>x.date===today).reduce((a,x)=>a+(Number(x.tests)||0),0); const w=typeof getWeekMetrics==='function'?getWeekMetrics():{study:0,tests:0};
 let streak=0,d=new Date();d.setHours(0,0,0,0);for(let i=0;i<365;i++){const k=typeof isoLocal==='function'?isoLocal(d):d.toISOString().slice(0,10);const active=(db.sessions||[]).some(x=>x.date===k)||(db.plans||[]).some(x=>x.date===k&&x.done);if(!active)break;streak++;d.setDate(d.getDate()-1)}
 return {m,tests,w,streak};
}
function bar(v,t){return Math.min(100,Math.round((v/Math.max(1,t))*100))}
function renderGoals(){const box=q('v202Goals');if(!box||!db)return;const g=db.settings.v202Goals||{};const x=goalMetrics();const cards=[['dailyStudy','هدف مطالعه امروز',x.m,g.dailyStudy||120,'دقیقه'],['dailyTests','هدف تست امروز',x.tests,g.dailyTests||20,'تست'],['weeklyStudy','هدف مطالعه هفته',x.w.study,g.weeklyStudy||0,'دقیقه'],['weeklyTests','هدف تست هفته',x.w.tests,g.weeklyTests||0,'تست'],['streak','هدف استریک',x.streak,g.streak||7,'روز']];box.innerHTML=cards.map(c=>{const pct=c[3]?bar(c[2],c[3]):0;const done=c[3]>0&&c[2]>=c[3];return `<div class="fp-v202-card ${done?'fp-v202-goal-complete':''}"><div class="fp-v202-row"><b>${c[0]==='streak'?'🔥 ':''}${c[1]}</b><span class="fp-v202-value">${fa(c[2])}</span></div><div class="fp-v202-progress"><i style="width:${pct}%"></i></div><div class="fp-v202-row fp-v202-muted"><span>${done?'هدف کامل شد ✓':'پیشرفت فعلی'}</span><span>${c[3]?fa(c[3])+' '+c[4]:'هدف تعیین نشده'}</span></div></div>`}).join('')}
function achievementData(){
 const base=typeof getAchievementList==='function'?getAchievementList():[]; const tier={first_login:'easy',study_60:'easy',plans_10:'easy',tests_100:'easy',week_active:'normal',study_600:'normal',tests_500:'normal',plans_50:'normal',streak_7:'normal',week_study_100:'normal',study_1500:'hard',tests_1000:'hard',plans_100:'hard',streak_14:'hard',perfect_5:'hard',week_both_100:'hard',study_3000:'epic',tests_2500:'epic',streak_30:'epic',perfect_8:'epic',sessions_50:'epic',level_10:'epic',study_6000:'legendary',tests_5000:'legendary',streak_60:'legendary',level_20:'legendary',level_30:'legendary'};
 const names={easy:'آسان',normal:'متوسط',hard:'سخت',epic:'حماسی',legendary:'افسانه‌ای'};
 return base.map(a=>({...a,tier:tier[a.id]||'normal',tierName:names[tier[a.id]||'normal']}));
}
function renderAchievements(){
 const box=q('v202Achievements');if(!box||!db)return;
 const p=typeof getUserProgress==='function'?getUserProgress():{level:1,xp:0,current:0,next:100,percent:0};
 const names=['تازه‌کار','شروع‌کننده','پرتلاش','منظم','متمرکز','پیشرو','رقیب','قهرمان','نخبه','استاد','استاد تمرکز','فرمانده مطالعه','نابغه برنامه‌ریزی','افسانه‌ای','اسطوره','قله‌نشین','فاتح کنکور','ابر قهرمان','جاودانه','افسانه زنده'];
 const levelName=names[Math.min(names.length-1,Math.max(0,p.level-1))];
 const list=achievementData(),unlocked=list.filter(a=>a.unlocked).length,featured=typeof getFeaturedMedal==='function'?getFeaturedMedal():null;
 const filter=q('v202AchFilter')?.value||'all';
 const arr=list.filter(a=>filter==='all'||(filter==='unlocked'?a.unlocked:(filter==='locked'?!a.unlocked:a.tier===filter)));
 q('v202AchCount').textContent=`${fa(unlocked)} از ${fa(list.length)} دستاورد باز شده`;
 const levelCard=`<div class="fp-v202-level-panel"><div class="fp-v202-level-top"><div><span class="fp-v202-kicker">USER LEVEL</span><h3>سطح ${fa(p.level)} · ${esc(levelName)}</h3><p class="fp-v202-muted">${fa(p.xp)} XP</p></div><div class="fp-v202-level-badge">${fa(p.level)}</div></div><div class="fp-v202-progress"><i style="width:${p.percent}%"></i></div><div class="fp-v202-row fp-v202-muted"><span>${p.xp>=p.next?'سطح بعدی باز شد!':fa(p.next-p.xp)+' XP تا سطح بعد'}</span><b>${fa(p.percent)}٪</b></div></div>`;
 const featuredCard=featured?`<div class="fp-v202-featured-panel"><div class="fp-v202-featured-icon featured-medal-art">${medalSVG(medalVisual(featured),featured.icon)}</div><div><span class="fp-v202-kicker">DASHBOARD FEATURED MEDAL</span><h4>مدال نمایشی: ${esc(featured.title)}</h4><p class="fp-v202-muted">همین طرح دقیقاً در داشبورد هم نمایش داده می‌شود. برای تغییر، روی «نمایش در داشبورد» مدال موردنظر بزن.</p></div></div>`:'';
 const cards=arr.map(a=>`<div class="fp-v202-ach fp-tier-${a.tier} ${a.unlocked?'unlocked':'locked'}"><span class="fp-v202-status">${a.unlocked?'✓ باز شده':'قفل'}</span><div class="fp-v202-medal fp-v202-medal-real">${medalSVG(medalVisual(a),a.icon)}</div><span class="fp-v202-tier">سطح ${a.tierName}</span><b>${esc(a.title)}</b><small>${esc(a.desc)}</small>${a.unlocked?`<button type="button" class="medal-select-btn ${featured?.id===a.id?'selected':''}" onclick="setFeaturedMedal('${a.id}')" data-medal-id="${a.id}">${featured?.id===a.id?'★ مدال نمایشی داشبورد':'☆ نمایش در داشبورد'}</button>`:''}</div>`).join('');
 box.innerHTML=levelCard+featuredCard+(cards||'<div class="fp-v202-search-empty">موردی پیدا نشد.</div>');
}

function renderSubjectCards(){const box=q('v202Subjects');if(!box)return;const arr=subjList();box.innerHTML=arr.map((s,i)=>{const m=minsForSubject(s),t=testsForSubject(s),p=plansForSubject(s),d=doneForSubject(s);return `<div class="fp-v202-subject" data-v202-sub="${esc(s)}"><div class="fp-v202-subject-top"><div><b>${esc(s)}</b><div class="fp-v202-muted">برای مشاهده جزئیات درس بزن</div></div><div class="fp-v202-subject-icon">${esc(String(s).trim().slice(0,2))}</div></div><div class="fp-v202-subject-stats"><div><span>مطالعه</span><b>${fa(m)} د</b></div><div><span>تست</span><b>${fa(t)}</b></div><div><span>برنامه</span><b>${fa(d)}/${fa(p)}</b></div></div></div>`}).join('')||'<div class="fp-v202-search-empty">هنوز درسی ثبت نشده است.</div>';box.querySelectorAll('[data-v202-sub]').forEach(e=>e.addEventListener('click',()=>openSubjectDetail(e.dataset.v202Sub)))}
function noteList(s){const arr=Array.isArray(db.subjectNotesPro?.[s])?db.subjectNotesPro[s]:[];return arr.sort((a,b)=>(b.updatedAt||0)-(a.updatedAt||0))}
function renderSubjectNotes(s){const box=q('v202NotesList');if(!box)return;const arr=noteList(s);box.innerHTML=arr.map((n,i)=>`<div class="fp-v202-note-item"><div>${esc(n.text||'')}</div><div>${(n.tags||[]).map(t=>`<span class="fp-v202-chip">${esc(t)}</span>`).join('')}</div><div class="meta">${n.updatedAt?new Date(n.updatedAt).toLocaleString('fa-IR'):''}</div><div class="fp-v202-note-toolbar"><button class="btn secondary" data-note-del="${i}">حذف</button></div></div>`).join('')||'<div class="fp-v202-search-empty">برای این درس هنوز یادداشتی ثبت نشده.</div>';box.querySelectorAll('[data-note-del]').forEach(b=>b.onclick=()=>{const a=noteList(s);a.splice(Number(b.dataset.noteDel),1);db.subjectNotesPro[s]=a;dbSave();renderSubjectNotes(s);});}
function openSubjectDetail(s){const modal=q('v202SubjectModal');if(!modal)return;modal.dataset.subject=s;q('v202SubjectTitle').textContent=s;const m=minsForSubject(s),t=testsForSubject(s),p=plansForSubject(s),d=doneForSubject(s);q('v202SubjectDetail').innerHTML=`<div class="fp-v202-detail-grid"><div><span>مطالعه واقعی</span><b>${fa(m)} دقیقه</b></div><div><span>تست</span><b>${fa(t)}</b></div><div><span>تعداد برنامه</span><b>${fa(p)}</b></div><div><span>انجام‌شده</span><b>${fa(d)}</b></div></div><div class="fp-v202-note"><h5>مبحث‌های ثبت‌شده</h5>${(()=>{const topics=[...new Set((db.plans||[]).filter(x=>x.subject===s&&x.topic).map(x=>x.topic))];return topics.length?topics.map(x=>`<span class="fp-v202-chip">${esc(x)}</span>`).join(''):'<span class="fp-v202-muted">مبحثی ثبت نشده.</span>'})()}</div>`;q('v202NoteSubject').value=s;q('v202NoteText').value='';q('v202NoteTags').value='';renderSubjectNotes(s);modal.classList.add('show')}
function saveSubjectNote(){const s=q('v202NoteSubject').value,t=(q('v202NoteText').value||'').trim();if(!s||!t){alert('درس و متن یادداشت را وارد کن.');return}db.subjectNotesPro=db.subjectNotesPro||{};db.subjectNotesPro[s]=noteList(s);db.subjectNotesPro[s].unshift({id:Date.now().toString(36),text:t,tags:(q('v202NoteTags').value||'').split(',').map(x=>x.trim()).filter(Boolean),updatedAt:Date.now()});dbSave();q('v202NoteText').value='';q('v202NoteTags').value='';renderSubjectNotes(s);}
function professionalSearch(){const input=q('fpGlobalSearch');const box=q('fpSearchResults');if(!input||!box||input.dataset.v202)return;input.dataset.v202='1';const old=window.__fpOriginalSearchInputHandler; input.addEventListener('input',()=>{const term=input.value.trim().toLocaleLowerCase('fa-IR');if(!term)return;const rows=[];const add=(type,title,detail,fn)=>rows.push({type,title,detail,fn});(db.plans||[]).forEach(x=>{if((x.subject+' '+x.topic+' '+x.tags).toLocaleLowerCase('fa-IR').includes(term))add('برنامه',x.subject||'برنامه',`${formatScheduleDate(x.date)} · ${x.topic||''}`,()=>{const b=document.querySelector('.focusplan-tabs button[data-tab="plan"]');if(b)b.click();setTimeout(()=>{document.getElementById('planList')?.scrollIntoView({behavior:'smooth',block:'center'})},80)})});(db.testTasks||[]).forEach(x=>{if((x.subject+' '+x.topic+' '+x.tags).toLocaleLowerCase('fa-IR').includes(term))add('تست',x.subject||'تست',`${formatScheduleDate(x.date)} · ${x.topic||''}`,()=>{const b=document.querySelector('.focusplan-tabs button[data-tab="plan"]');if(b)b.click();setTimeout(()=>document.querySelector('.test-manager-card')?.scrollIntoView({behavior:'smooth',block:'center'}),80)})});Object.entries(db.subjectNotesPro||{}).forEach(([s,a])=>(a||[]).forEach(n=>{if((s+' '+n.text+' '+(n.tags||[]).join(' ')).toLocaleLowerCase('fa-IR').includes(term))add('یادداشت',s,n.text.slice(0,100),()=>openSubjectDetail(s))}));subjList().forEach(s=>{if(String(s).toLocaleLowerCase('fa-IR').includes(term))add('درس',s,'صفحه جزئیات درس',()=>openSubjectDetail(s))});if(!rows.length)return;const unique=[];const seen=new Set();rows.forEach(r=>{const k=r.type+'|'+r.title+'|'+r.detail;if(!seen.has(k)){seen.add(k);unique.push(r)}});box.innerHTML=`<div class="fp-v202-search-result" style="cursor:default"><b>نتایج حرفه‌ای جستجو</b><small>${fa(unique.length)} نتیجه</small></div>`+unique.slice(0,20).map((r,i)=>`<div class="fp-v202-search-result" data-v202-search="${i}"><b><span class="fp-v202-chip">${esc(r.type)}</span>${esc(r.title)}</b><small>${esc(r.detail)}</small></div>`).join('');box.hidden=false;box.querySelectorAll('[data-v202-search]').forEach(e=>e.onclick=()=>unique[Number(e.dataset.v202Search)].fn())});}
function buildUI(){
 if(!db||q('v202GoalsSection'))return;ensureV202Data();
 const tabs=document.querySelector('.focusplan-tabs');const perf=tabs?.querySelector('[data-tab="performance"]');if(tabs&&perf){const b=document.createElement('button');b.className='btn secondary';b.dataset.tab='achievements';b.textContent='دستاوردها';perf.insertAdjacentElement('afterend',b);b.onclick=function(){document.querySelectorAll('.tabs button').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.section').forEach(x=>x.classList.remove('active','fp-enter'));b.classList.add('active');const sec=q('achievements');if(sec){sec.classList.add('active','fp-enter');setTimeout(()=>{renderGoals();renderAchievements()},0)}}}
 const main=document.querySelector('main');if(!main)return;
 const more=q('moreFeatures');
 const sec=document.createElement('section');sec.id='achievements';sec.className='section';sec.innerHTML=`<h2>دستاوردها و هدف‌ها 🏆</h2><div id="v202GoalsSection" class="fp-v202-wrap"><div class="card"><div class="fp-v202-head"><div><span class="fp-v202-kicker">GOAL SYSTEM PRO</span><h3>هدف‌گذاری حرفه‌ای</h3><p class="fp-v202-muted">هدف‌ها را برای امروز، این هفته و استریک تنظیم کن و پیشرفتشان را یک‌جا ببین.</p></div></div><div class="fp-v202-form"><label>مطالعه روزانه<input id="v202_dailyStudy" type="number" min="1" step="5"></label><label>تست روزانه<input id="v202_dailyTests" type="number" min="1"></label><label>مطالعه هفتگی<input id="v202_weeklyStudy" type="number" min="1" step="15"></label><label>تست هفتگی<input id="v202_weeklyTests" type="number" min="1"></label><label>هدف استریک<input id="v202_streak" type="number" min="1"></label></div><div class="fp-v202-actions"><button class="btn" id="v202SaveGoals">ذخیره هدف‌ها</button><button class="btn secondary" id="v202SyncGoals">هماهنگ با اهداف فعلی FocusPlan</button></div><div id="v202Goals" class="fp-v202-grid" style="margin-top:14px"></div></div><br><div class="card"><div class="fp-v202-head"><div><span class="fp-v202-kicker">ACHIEVEMENTS PRO</span><h3>مدال‌ها و دستاوردها</h3><p class="fp-v202-muted" id="v202AchCount"></p></div><select id="v202AchFilter" style="max-width:170px"><option value="all">همه</option><option value="unlocked">بازشده‌ها</option><option value="locked">قفل‌شده‌ها</option><option value="easy">آسان</option><option value="normal">متوسط</option><option value="hard">سخت</option><option value="epic">حماسی</option><option value="legendary">افسانه‌ای</option></select></div><div id="v202Achievements" class="fp-v202-ach-grid"></div></div></div>`;
 main.insertBefore(sec,more||main.lastElementChild);
 const moreSec=more;if(moreSec){const card=document.createElement('div');card.className='card fp-v202-wrap';card.innerHTML=`<div class="fp-v202-head"><div><span class="fp-v202-kicker">SUBJECT HUB</span><h3>صفحه جزئیات هر درس</h3><p class="fp-v202-muted">هر درس را جداگانه باز کن و مطالعه، تست، برنامه‌ها، مباحث و یادداشت‌های حرفه‌ای آن را ببین.</p></div></div><div id="v202Subjects" class="fp-v202-subject-grid"></div>`;moreSec.insertBefore(card,moreSec.firstChild)}
 const planSec=q('plan');if(planSec){const card=document.createElement('div');card.className='card fp-v202-wrap';card.innerHTML=`<div class="fp-v202-head"><div><span class="fp-v202-kicker">SUBJECT NOTES PRO</span><h3>یادداشت حرفه‌ای درس‌ها</h3><p class="fp-v202-muted">یادداشت‌های هر درس جدا ذخیره می‌شوند و از جستجوی سراسری هم قابل پیدا کردن هستند.</p></div></div><div class="fp-v202-form"><label>درس<select id="v202NoteSubject"></select></label><label style="grid-column:span 2">برچسب‌ها<input id="v202NoteTags" placeholder="مثلاً نکته، مرور، مهم"></label></div><textarea id="v202NoteText" rows="4" placeholder="یادداشت حرفه‌ای این درس..."></textarea><div class="fp-v202-actions"><button class="btn" id="v202SaveNote">ذخیره یادداشت</button></div></div>`;planSec.insertBefore(card,planSec.children[2]||planSec.firstChild)}
 const modal=document.createElement('div');modal.id='v202SubjectModal';modal.className='fp-v202-modal';modal.innerHTML=`<div class="fp-v202-modal-box"><div class="fp-v202-modal-head"><div><span class="fp-v202-kicker">SUBJECT DETAIL</span><h3 id="v202SubjectTitle">درس</h3></div><button class="fp-v202-close" id="v202SubjectClose">×</button></div><div id="v202SubjectDetail"></div><div class="fp-v202-note"><h5>یادداشت جدید</h5><textarea id="v202NoteTextModal" rows="4" placeholder="نکته، فرمول، اشتباهات رایج، برنامه مرور و..."></textarea><input id="v202NoteTagsModal" placeholder="برچسب‌ها با ویرگول"><div class="fp-v202-actions"><button class="btn" id="v202SaveNoteModal">ذخیره در همین درس</button></div></div><div class="fp-v202-note"><h5>یادداشت‌های این درس</h5><div id="v202NotesList" class="fp-v202-notes-list"></div></div></div>`;document.body.appendChild(modal);
 q('v202SaveGoals').onclick=saveGoals;q('v202AchFilter').onchange=renderAchievements;q('v202SaveNote').onclick=()=>{const s=q('v202NoteSubject').value,t=(q('v202NoteText').value||'').trim(),tags=(q('v202NoteTags').value||'').split(',').map(x=>x.trim()).filter(Boolean);if(!s||!t){alert('درس و متن یادداشت را وارد کن.');return}db.subjectNotesPro=db.subjectNotesPro||{};db.subjectNotesPro[s]=noteList(s);db.subjectNotesPro[s].unshift({id:Date.now().toString(36),text:t,tags:tags,updatedAt:Date.now()});dbSave();q('v202NoteText').value='';q('v202NoteTags').value='';renderSubjectCards()};q('v202SubjectClose').onclick=()=>modal.classList.remove('show');modal.addEventListener('click',e=>{if(e.target===modal)modal.classList.remove('show')});q('v202SaveNoteModal').onclick=saveSubjectNoteModal;
 const sync=q('v202SyncGoals');sync.onclick=()=>{const g=db.settings.v202Goals||{};g.weeklyStudy=getActiveWeeklyStudyGoal?getActiveWeeklyStudyGoal():g.weeklyStudy;g.weeklyTests=getActiveWeeklyTestGoal?getActiveWeeklyTestGoal():g.weeklyTests;g.dailyStudy=db.settings.goal||g.dailyStudy;db.settings.v202Goals=g;dbSave();fillGoalInputs();renderGoals()};
 fillGoalInputs();const ns=subjList();const selects=[q('v202NoteSubject')].filter(Boolean);selects.forEach(sel=>{sel.innerHTML=ns.map(s=>`<option value="${esc(s)}">${esc(s)}</option>`).join('')});
 renderGoals();renderAchievements();renderSubjectCards();professionalSearch();
 setTimeout(()=>{try{renderDashboardIdentity()}catch(e){}},0);
 document.querySelectorAll('.focusplan-tabs button[data-tab="achievements"]').forEach(b=>b.addEventListener('click',()=>{renderGoals();renderAchievements()}));
 const oldRender=window.render;if(typeof oldRender==='function'&&!oldRender.__v202){window.render=function(){const r=oldRender.apply(this,arguments);setTimeout(()=>{renderGoals();renderAchievements();renderSubjectCards()},0);return r};window.render.__v202=true}
}
function fillGoalInputs(){const g=db.settings.v202Goals||{};['dailyStudy','dailyTests','weeklyStudy','weeklyTests','streak'].forEach(k=>{const e=q('v202_'+k);if(e)e.value=g[k]||''})}
function saveSubjectNoteModal(){const s=q('v202SubjectModal').dataset.subject,t=(q('v202NoteTextModal').value||'').trim();if(!s||!t){alert('متن یادداشت را وارد کن.');return}db.subjectNotesPro=db.subjectNotesPro||{};db.subjectNotesPro[s]=noteList(s);db.subjectNotesPro[s].unshift({id:Date.now().toString(36),text:t,tags:(q('v202NoteTagsModal').value||'').split(',').map(x=>x.trim()).filter(Boolean),updatedAt:Date.now()});dbSave();q('v202NoteTextModal').value='';q('v202NoteTagsModal').value='';renderSubjectNotes(s);renderSubjectCards()}
function init(){if(typeof db==='undefined'||!db)return;setTimeout(buildUI,250)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
window.openV202SubjectDetail=openSubjectDetail;
})();
